const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
const API_CONSTANTS = {
  CREATE_ACCOUNT: `${BASE_URL}/createUserAccount`,
  AUTHENTICATE_USER: `${BASE_URL}/authenticateUser`,
  CREATE_PROJECT: `${BASE_URL}/createNewProjectByUser`,
  GET_ALL_PROJS_BY_USER: `${BASE_URL}/getAllProjectsByUser`,
  GET_PROJ_BY_ID: `${BASE_URL}/getProjectById`,
  UPDATE_PROJ: `${BASE_URL}/updateProject`,
  CREATE_PG: `${BASE_URL}/createNewPgByUser`,
  GET_ALL_PGS_BY_USER: `${BASE_URL}/getAllPgsByUser`,
  GET_PG_BY_ID: `${BASE_URL}/getPgById`,
  UPDATE_PG: `${BASE_URL}/updatePg`,
  CREATE_WB: `${BASE_URL}/createNewWbByUser`,
  GET_ALL_WBS_BY_USER: `${BASE_URL}/getAllWbsByUser`,
  GET_WB_BY_ID: `${BASE_URL}/getWbById`,
  UPDATE_WB: `${BASE_URL}/updateWb`,
  COMPILE: `${BASE_URL}/compile`,
  SEARCH_USERS: `${BASE_URL}/getProfilesByName`,
  SEARCH_PROJS: `${BASE_URL}/getProjsByName`,
  SEARCH_PGS: `${BASE_URL}/getPgsByName`,
  SEARCH_WBS: `${BASE_URL}/getWbsByName`,
  CONNECTION_REQ: `${BASE_URL}/connectionReq`,
  CONNECTION_STATUS: `${BASE_URL}/connectionStatus`,
  ADD_CONNECTION: `${BASE_URL}/addConnection`,
  REJECT_CONNECTION_REQ: `${BASE_URL}/rejectConnectionReq`,
  GET_ALL_CONN_REQS: `${BASE_URL}/getAllConnectionReqs`,
  REMOVE_CONNECTION: `${BASE_URL}/removeConnection`,
  GET_CONNECTIONS_BY_USER: `${BASE_URL}/connectionByUser`,
  USER_INFO: `${BASE_URL}/userInfo`,
  GET_OTP: `${BASE_URL}/getVerificationCode`,
  VALIDATE_OTP: `${BASE_URL}/validateOtp`,
  UPDATE_PASSWORD: `${BASE_URL}/updatePassword`,
  DELETE_PROJ: `${BASE_URL}/deleteProject`,
  DELETE_PG: `${BASE_URL}/deletePg`,
  DELETE_WB: `${BASE_URL}/deleteWb`,
  UPDATE_USER_DETAILS:`${BASE_URL}/updateUserDetails`
};

export default API_CONSTANTS;
